workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.fermemoutcho.app"
      android_signing:
        - keystore_reference
      groups:
        - google_play
    scripts:
      - name: Set up environment
        script: |
          #!/usr/bin/env sh
          set -e
          echo "Setting up environment..."
          
      - name: Install dependencies
        script: |
          #!/usr/bin/env sh
          set -e
          npm ci
          
      - name: Add Android platform
        script: |
          #!/usr/bin/env sh
          set -e
          npx cap add android
          
      - name: Sync project
        script: |
          #!/usr/bin/env sh
          set -e
          npx cap sync android
          
      - name: Build Android App Bundle
        script: |
          #!/usr/bin/env sh
          set -e
          cd android
          ./gradlew bundleRelease
          
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
        track: internal

  ios-workflow:
    name: iOS Build
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.fermemoutcho.app"
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
        - code_signing
    scripts:
      - name: Set up environment
        script: |
          #!/usr/bin/env sh
          set -e
          echo "Setting up iOS environment..."
          echo "Xcode version: $(xcodebuild -version)"
          echo "Current directory: $(pwd)"
          
      - name: Install dependencies
        script: |
          #!/usr/bin/env sh
          set -e
          npm ci
          
      - name: Add iOS platform
        script: |
          #!/usr/bin/env sh
          set -e
          npx cap add ios
          
      - name: Sync project
        script: |
          #!/usr/bin/env sh
          set -e
          npx cap sync ios
          
      - name: Install CocoaPods
        script: |
          #!/usr/bin/env sh
          set -e
          cd ios/App
          pod install --repo-update
          
      - name: List iOS project structure
        script: |
          #!/usr/bin/env sh
          set -e
          echo "iOS project structure:"
          ls -la ios/App/
          echo "Xcode project files:"
          ls -la ios/App/*.xcodeproj/
          
      - name: Build iOS Archive Only
        script: |
          #!/usr/bin/env sh
          set -e
          echo "Starting iOS archive build..."
          
          # Vérifier que le projet existe
          if [ ! -d "ios/App/App.xcworkspace" ]; then
            echo "Error: App.xcworkspace not found!"
            ls -la ios/App/
            exit 1
          fi
          
          # Build avec signing automatique
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath /tmp/App.xcarchive \
                     archive \
                     -verbose \
                     CODE_SIGN_STYLE=Automatic \
                     CODE_SIGN_IDENTITY="" \
                     DEVELOPMENT_TEAM="" \
                     PROVISIONING_PROFILE=""
          
          echo "iOS Archive created successfully!"
          echo "Note: IPA export requires development team configuration"
          echo "Archive available at: /tmp/App.xcarchive"
          
    artifacts:
      - /tmp/App.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true 